const mockMenus = {
  1: {
    info: {
      id: "1",
      name: "Burger King",
      image:
        "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800",
      cuisines: ["Burgers", "Fast Food", "Beverages"],
      avgRating: 4.4,
      costForTwo: "₹400 for two",
      areaName: "Connaught Place",
      locality: "New Delhi",
      sla: {
        deliveryTime: 25,
      },
    },

    menu: [
      {
        id: "101",
        name: "Whopper",
        price: 199,
        category: "Burgers",
        description: "Signature flame-grilled burger with fresh veggies.",
        isVeg: false,
      },
      {
        id: "102",
        name: "Veg Whopper",
        price: 179,
        category: "Burgers",
        description: "Classic veg burger with crispy patty.",
        isVeg: true,
      },
      {
        id: "103",
        name: "Chicken Fries",
        price: 169,
        category: "Sides",
        description: "Crispy chicken fries.",
        isVeg: false,
      },
      {
        id: "104",
        name: "French Fries",
        price: 109,
        category: "Sides",
        description: "Salted crispy fries.",
        isVeg: true,
      },
      {
        id: "105",
        name: "Coca Cola",
        price: 69,
        category: "Beverages",
        description: "Chilled soft drink.",
        isVeg: true,
      },
    ],
  },

  2: {
    info: {
      id: "2",
      name: "Pizza Hut",
      image:
        "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800",
      cuisines: ["Pizza", "Italian", "Desserts"],
      avgRating: 4.3,
      costForTwo: "₹500 for two",
      areaName: "Rajouri Garden",
      locality: "New Delhi",
      sla: {
        deliveryTime: 30,
      },
    },

    menu: [
      {
        id: "201",
        name: "Margherita Pizza",
        price: 249,
        category: "Pizza",
        description: "Classic cheese pizza.",
        isVeg: true,
      },
      {
        id: "202",
        name: "Farmhouse Pizza",
        price: 399,
        category: "Pizza",
        description: "Loaded with fresh vegetables.",
        isVeg: true,
      },
      {
        id: "203",
        name: "Chicken Supreme",
        price: 499,
        category: "Pizza",
        description: "Chicken topped pizza.",
        isVeg: false,
      },
      {
        id: "204",
        name: "Garlic Bread",
        price: 159,
        category: "Sides",
        description: "Fresh baked garlic bread.",
        isVeg: true,
      },
      {
        id: "205",
        name: "Chocolate Lava Cake",
        price: 109,
        category: "Desserts",
        description: "Warm chocolate dessert.",
        isVeg: true,
      },
    ],
  },

  3: {
    info: {
      id: "3",
      name: "KFC",
      image:
        "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=800",
      cuisines: ["Chicken", "Fast Food", "Burgers"],
      avgRating: 4.2,
      costForTwo: "₹550 for two",
      areaName: "Sector 18",
      locality: "Noida",
      sla: {
        deliveryTime: 28,
      },
    },

    menu: [
      {
        id: "301",
        name: "Zinger Burger",
        price: 229,
        category: "Burgers",
        description: "Spicy crispy chicken burger.",
        isVeg: false,
      },
      {
        id: "302",
        name: "Hot & Crispy Chicken",
        price: 329,
        category: "Chicken",
        description: "Signature crispy chicken.",
        isVeg: false,
      },
      {
        id: "303",
        name: "Chicken Bucket",
        price: 699,
        category: "Buckets",
        description: "8 pcs crispy chicken.",
        isVeg: false,
      },
      {
        id: "304",
        name: "French Fries",
        price: 119,
        category: "Sides",
        description: "Golden fries.",
        isVeg: true,
      },
      {
        id: "305",
        name: "Pepsi",
        price: 79,
        category: "Beverages",
        description: "Cold drink.",
        isVeg: true,
      },
    ],
  },

  4: {
    info: {
      id: "4",
      name: "Domino's Pizza",
      image: "https://images.unsplash.com/photo-1548365328-9f547fb0953b?w=800",
      cuisines: ["Pizza", "Italian", "Fast Food"],
      avgRating: 4.5,
      costForTwo: "₹600 for two",
      areaName: "Indirapuram",
      locality: "Ghaziabad",
      sla: {
        deliveryTime: 24,
      },
    },

    menu: [
      {
        id: "401",
        name: "Cheese Burst Pizza",
        price: 499,
        category: "Pizza",
        description: "Loaded cheese burst pizza.",
        isVeg: true,
      },
      {
        id: "402",
        name: "Pepper Barbecue Chicken",
        price: 459,
        category: "Pizza",
        description: "Chicken pizza with BBQ sauce.",
        isVeg: false,
      },
      {
        id: "403",
        name: "Garlic Breadsticks",
        price: 149,
        category: "Sides",
        description: "Fresh baked garlic bread.",
        isVeg: true,
      },
      {
        id: "404",
        name: "Taco Mexicana",
        price: 199,
        category: "Sides",
        description: "Cheesy taco snack.",
        isVeg: true,
      },
      {
        id: "405",
        name: "Choco Lava Cake",
        price: 109,
        category: "Desserts",
        description: "Chocolate filled cake.",
        isVeg: true,
      },
    ],
  },

  5: {
    info: {
      id: "5",
      name: "Subway",
      image: "https://images.unsplash.com/photo-1553909489-cd47e0907980?w=800",
      cuisines: ["Healthy Food", "Sandwiches", "Salads"],
      avgRating: 4.1,
      costForTwo: "₹450 for two",
      areaName: "Lajpat Nagar",
      locality: "New Delhi",
      sla: {
        deliveryTime: 22,
      },
    },

    menu: [
      {
        id: "501",
        name: "Veggie Delight",
        price: 229,
        category: "Subs",
        description: "Fresh vegetable sub.",
        isVeg: true,
      },
      {
        id: "502",
        name: "Paneer Tikka Sub",
        price: 299,
        category: "Subs",
        description: "Paneer tikka loaded sub.",
        isVeg: true,
      },
      {
        id: "503",
        name: "Chicken Teriyaki",
        price: 349,
        category: "Subs",
        description: "Chicken teriyaki sandwich.",
        isVeg: false,
      },
      {
        id: "504",
        name: "Chocolate Cookie",
        price: 59,
        category: "Desserts",
        description: "Fresh baked cookie.",
        isVeg: true,
      },
      {
        id: "505",
        name: "Sprite",
        price: 79,
        category: "Beverages",
        description: "Cold soft drink.",
        isVeg: true,
      },
    ],
  },
  6: {
    info: {
      id: "6",
      name: "McDonald's",
      image: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=800",
      cuisines: ["Burgers", "Fast Food", "Beverages"],
      avgRating: 4.3,
      costForTwo: "₹400 for two",
      areaName: "Sector 62",
      locality: "Noida",
      sla: {
        deliveryTime: 20,
      },
    },

    menu: [
      {
        id: "601",
        name: "McAloo Tikki Burger",
        price: 79,
        category: "Burgers",
        description: "India's favourite McAloo Tikki Burger.",
        isVeg: true,
      },
      {
        id: "602",
        name: "McVeggie Burger",
        price: 189,
        category: "Burgers",
        description: "Loaded with fresh veggies.",
        isVeg: true,
      },
      {
        id: "603",
        name: "McChicken Burger",
        price: 219,
        category: "Burgers",
        description: "Classic chicken burger.",
        isVeg: false,
      },
      {
        id: "604",
        name: "Fries",
        price: 109,
        category: "Sides",
        description: "Golden crispy fries.",
        isVeg: true,
      },
      {
        id: "605",
        name: "McFloat Coke",
        price: 99,
        category: "Beverages",
        description: "Coke with vanilla soft serve.",
        isVeg: true,
      },
    ],
  },

  7: {
    info: {
      id: "7",
      name: "Biryani Blues",
      image:
        "https://images.unsplash.com/photo-1563379091339-03246963d29a?w=800",
      cuisines: ["Biryani", "North Indian"],
      avgRating: 4.6,
      costForTwo: "₹700 for two",
      areaName: "Karol Bagh",
      locality: "New Delhi",
      sla: {
        deliveryTime: 30,
      },
    },

    menu: [
      {
        id: "701",
        name: "Hyderabadi Chicken Biryani",
        price: 349,
        category: "Biryani",
        description: "Authentic Hyderabadi dum biryani.",
        isVeg: false,
      },
      {
        id: "702",
        name: "Veg Dum Biryani",
        price: 279,
        category: "Biryani",
        description: "Fragrant veg dum biryani.",
        isVeg: true,
      },
      {
        id: "703",
        name: "Paneer Tikka",
        price: 249,
        category: "Starters",
        description: "Char-grilled paneer cubes.",
        isVeg: true,
      },
      {
        id: "704",
        name: "Raita",
        price: 49,
        category: "Sides",
        description: "Fresh curd with spices.",
        isVeg: true,
      },
      {
        id: "705",
        name: "Gulab Jamun",
        price: 79,
        category: "Desserts",
        description: "Soft gulab jamun.",
        isVeg: true,
      },
    ],
  },

  8: {
    info: {
      id: "8",
      name: "Behrouz Biryani",
      image:
        "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=800",
      cuisines: ["Biryani", "Mughlai"],
      avgRating: 4.5,
      costForTwo: "₹800 for two",
      areaName: "Dwarka",
      locality: "New Delhi",
      sla: {
        deliveryTime: 32,
      },
    },

    menu: [
      {
        id: "801",
        name: "Royal Chicken Biryani",
        price: 429,
        category: "Biryani",
        description: "Premium chicken biryani.",
        isVeg: false,
      },
      {
        id: "802",
        name: "Paneer Biryani",
        price: 329,
        category: "Biryani",
        description: "Rich paneer dum biryani.",
        isVeg: true,
      },
      {
        id: "803",
        name: "Chicken Kebab",
        price: 299,
        category: "Starters",
        description: "Juicy chicken kebabs.",
        isVeg: false,
      },
      {
        id: "804",
        name: "Firni",
        price: 99,
        category: "Desserts",
        description: "Traditional Mughlai dessert.",
        isVeg: true,
      },
      {
        id: "805",
        name: "Soft Drink",
        price: 69,
        category: "Beverages",
        description: "Chilled beverage.",
        isVeg: true,
      },
    ],
  },

  9: {
    info: {
      id: "9",
      name: "Wow! Momo",
      image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800",
      cuisines: ["Momos", "Chinese", "Tibetan"],
      avgRating: 4.2,
      costForTwo: "₹350 for two",
      areaName: "Rohini",
      locality: "New Delhi",
      sla: {
        deliveryTime: 19,
      },
    },

    menu: [
      {
        id: "901",
        name: "Steamed Veg Momos",
        price: 149,
        category: "Momos",
        description: "Classic steamed veg momos.",
        isVeg: true,
      },
      {
        id: "902",
        name: "Fried Chicken Momos",
        price: 199,
        category: "Momos",
        description: "Crispy fried chicken momos.",
        isVeg: false,
      },
      {
        id: "903",
        name: "Pan Fried Momos",
        price: 229,
        category: "Momos",
        description: "Pan tossed spicy momos.",
        isVeg: false,
      },
      {
        id: "904",
        name: "Momo Platter",
        price: 299,
        category: "Combos",
        description: "Assorted momo platter.",
        isVeg: false,
      },
      {
        id: "905",
        name: "Iced Tea",
        price: 89,
        category: "Beverages",
        description: "Refreshing iced tea.",
        isVeg: true,
      },
    ],
  },

  10: {
    info: {
      id: "10",
      name: "Haldiram's",
      image:
        "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800",
      cuisines: ["North Indian", "Snacks", "Sweets"],
      avgRating: 4.4,
      costForTwo: "₹500 for two",
      areaName: "Connaught Place",
      locality: "New Delhi",
      sla: {
        deliveryTime: 26,
      },
    },

    menu: [
      {
        id: "1001",
        name: "Chole Bhature",
        price: 179,
        category: "North Indian",
        description: "Classic Delhi style chole bhature.",
        isVeg: true,
      },
      {
        id: "1002",
        name: "Raj Kachori",
        price: 159,
        category: "Snacks",
        description: "Stuffed crispy raj kachori.",
        isVeg: true,
      },
      {
        id: "1003",
        name: "Pav Bhaji",
        price: 169,
        category: "Snacks",
        description: "Butter loaded pav bhaji.",
        isVeg: true,
      },
      {
        id: "1004",
        name: "Rasmalai",
        price: 109,
        category: "Desserts",
        description: "Soft rasmalai in creamy milk.",
        isVeg: true,
      },
      {
        id: "1005",
        name: "Sweet Lassi",
        price: 99,
        category: "Beverages",
        description: "Refreshing Punjabi lassi.",
        isVeg: true,
      },
    ],
  },
  11: {
    info: {
      id: "11",
      name: "Bikanervala",
      image:
        "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800",
      cuisines: ["North Indian", "Sweets", "Snacks"],
      avgRating: 4.3,
      costForTwo: "₹500 for two",
      areaName: "Sector 18",
      locality: "Noida",
      sla: {
        deliveryTime: 27,
      },
    },

    menu: [
      {
        id: "1101",
        name: "Pav Bhaji",
        price: 189,
        category: "Snacks",
        description: "Butter loaded Mumbai style pav bhaji.",
        isVeg: true,
      },
      {
        id: "1102",
        name: "Chole Kulche",
        price: 169,
        category: "North Indian",
        description: "Punjabi style chole with soft kulche.",
        isVeg: true,
      },
      {
        id: "1103",
        name: "Samosa",
        price: 49,
        category: "Snacks",
        description: "Crispy aloo samosa.",
        isVeg: true,
      },
      {
        id: "1104",
        name: "Rasgulla",
        price: 89,
        category: "Desserts",
        description: "Soft Bengali rasgulla.",
        isVeg: true,
      },
      {
        id: "1105",
        name: "Mango Lassi",
        price: 99,
        category: "Beverages",
        description: "Sweet mango flavored lassi.",
        isVeg: true,
      },
    ],
  },

  12: {
    info: {
      id: "12",
      name: "Barbeque Nation",
      image:
        "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=800",
      cuisines: ["BBQ", "North Indian", "Chinese"],
      avgRating: 4.7,
      costForTwo: "₹1800 for two",
      areaName: "Cyber Hub",
      locality: "Gurugram",
      sla: {
        deliveryTime: 35,
      },
    },

    menu: [
      {
        id: "1201",
        name: "Chicken BBQ Platter",
        price: 599,
        category: "BBQ",
        description: "Smoky grilled chicken platter.",
        isVeg: false,
      },
      {
        id: "1202",
        name: "Paneer Tikka",
        price: 349,
        category: "BBQ",
        description: "Charcoal grilled paneer tikka.",
        isVeg: true,
      },
      {
        id: "1203",
        name: "Tandoori Prawns",
        price: 649,
        category: "Sea Food",
        description: "Grilled spicy prawns.",
        isVeg: false,
      },
      {
        id: "1204",
        name: "Brownie with Ice Cream",
        price: 149,
        category: "Desserts",
        description: "Warm brownie served with vanilla ice cream.",
        isVeg: true,
      },
      {
        id: "1205",
        name: "Fresh Lime Soda",
        price: 119,
        category: "Beverages",
        description: "Refreshing lime soda.",
        isVeg: true,
      },
    ],
  },

  13: {
    info: {
      id: "13",
      name: "Chaayos",
      image:
        "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
      cuisines: ["Tea", "Cafe", "Snacks"],
      avgRating: 4.5,
      costForTwo: "₹300 for two",
      areaName: "South Extension",
      locality: "New Delhi",
      sla: {
        deliveryTime: 18,
      },
    },

    menu: [
      {
        id: "1301",
        name: "Masala Chai",
        price: 99,
        category: "Tea",
        description: "Signature masala chai.",
        isVeg: true,
      },
      {
        id: "1302",
        name: "Bun Maska",
        price: 89,
        category: "Snacks",
        description: "Fresh bun with butter.",
        isVeg: true,
      },
      {
        id: "1303",
        name: "Poha",
        price: 129,
        category: "Breakfast",
        description: "Indore style poha.",
        isVeg: true,
      },
      {
        id: "1304",
        name: "Cheese Sandwich",
        price: 169,
        category: "Sandwich",
        description: "Grilled cheese sandwich.",
        isVeg: true,
      },
      {
        id: "1305",
        name: "Cold Coffee",
        price: 149,
        category: "Beverages",
        description: "Creamy cold coffee.",
        isVeg: true,
      },
    ],
  },

  14: {
    info: {
      id: "14",
      name: "Starbucks",
      image:
        "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
      cuisines: ["Coffee", "Bakery", "Desserts"],
      avgRating: 4.6,
      costForTwo: "₹700 for two",
      areaName: "Saket",
      locality: "New Delhi",
      sla: {
        deliveryTime: 17,
      },
    },

    menu: [
      {
        id: "1401",
        name: "Cappuccino",
        price: 299,
        category: "Coffee",
        description: "Rich espresso with steamed milk.",
        isVeg: true,
      },
      {
        id: "1402",
        name: "Cafe Latte",
        price: 319,
        category: "Coffee",
        description: "Smooth latte coffee.",
        isVeg: true,
      },
      {
        id: "1403",
        name: "Blueberry Muffin",
        price: 199,
        category: "Bakery",
        description: "Fresh baked blueberry muffin.",
        isVeg: true,
      },
      {
        id: "1404",
        name: "Chocolate Brownie",
        price: 229,
        category: "Desserts",
        description: "Rich chocolate brownie.",
        isVeg: true,
      },
      {
        id: "1405",
        name: "Java Chip Frappuccino",
        price: 399,
        category: "Coffee",
        description: "Blended coffee with chocolate chips.",
        isVeg: true,
      },
    ],
  },

  15: {
    info: {
      id: "15",
      name: "The Belgian Waffle Co.",
      image: "https://images.unsplash.com/photo-1562376552-0d160a2f238d?w=800",
      cuisines: ["Desserts", "Waffles", "Beverages"],
      avgRating: 4.8,
      costForTwo: "₹450 for two",
      areaName: "Pitampura",
      locality: "New Delhi",
      sla: {
        deliveryTime: 21,
      },
    },

    menu: [
      {
        id: "1501",
        name: "Chocolate Waffle",
        price: 249,
        category: "Waffles",
        description: "Belgian waffle with chocolate sauce.",
        isVeg: true,
      },
      {
        id: "1502",
        name: "Nutella Waffle",
        price: 299,
        category: "Waffles",
        description: "Loaded Nutella waffle.",
        isVeg: true,
      },
      {
        id: "1503",
        name: "Red Velvet Waffle",
        price: 319,
        category: "Waffles",
        description: "Soft red velvet waffle.",
        isVeg: true,
      },
      {
        id: "1504",
        name: "Belgian Chocolate Shake",
        price: 229,
        category: "Beverages",
        description: "Creamy chocolate shake.",
        isVeg: true,
      },
      {
        id: "1505",
        name: "Vanilla Ice Cream",
        price: 129,
        category: "Desserts",
        description: "Classic vanilla scoop.",
        isVeg: true,
      },
    ],
  },
};

export default mockMenus;
